# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0003_auto_20161020_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfers',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0441'),
        ),
        migrations.AddField(
            model_name='banktransfers',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AddField(
            model_name='banktransfers',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='banktransfers',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0418\u043c\u044f \u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044f'),
        ),
        migrations.AlterField(
            model_name='banktransfers',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='banktransfers',
            name='from_bank',
            field=models.CharField(max_length=255, verbose_name='from bank'),
        ),
        migrations.AlterField(
            model_name='banktransfers',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='banktransfers',
            name='status',
            field=models.CharField(choices=[('created', '\u0441\u043e\u0437\u0434\u0430\u043d'), ('processing', '\u0432 \u0440\u0430\u0431\u043e\u0442\u0435'), ('processed', '\u043e\u0431\u0440\u0430\u0431\u043e\u0442\u0430\u043d'), ('invest', '\u043f\u0440\u043e\u0438\u043d\u0432\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d'), ('refund', '\u0441\u0434\u0435\u043b\u043a\u0430'), ('canceled', '\u043e\u0442\u043c\u0435\u043d\u0435\u043d')], default='created', max_length=40),
        ),
        migrations.AlterField(
            model_name='investdeals',
            name='status',
            field=models.CharField(choices=[('created', '\u0441\u043e\u0437\u0434\u0430\u043d'), ('processing', '\u0432 \u0440\u0430\u0431\u043e\u0442\u0435'), ('processed', '\u043e\u0431\u0440\u0430\u0431\u043e\u0442\u0430\u043d'), ('invest', '\u043f\u0440\u043e\u0438\u043d\u0432\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d'), ('refund', '\u0441\u0434\u0435\u043b\u043a\u0430'), ('canceled', '\u043e\u0442\u043c\u0435\u043d\u0435\u043d')], default='created', max_length=40),
        ),
        migrations.AlterField(
            model_name='trans',
            name='status',
            field=models.CharField(choices=[('created', '\u0441\u043e\u0437\u0434\u0430\u043d'), ('processing', '\u0432 \u0440\u0430\u0431\u043e\u0442\u0435'), ('processed', '\u043e\u0431\u0440\u0430\u0431\u043e\u0442\u0430\u043d'), ('invest', '\u043f\u0440\u043e\u0438\u043d\u0432\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d'), ('refund', '\u0441\u0434\u0435\u043b\u043a\u0430'), ('canceled', '\u043e\u0442\u043c\u0435\u043d\u0435\u043d')], default='created', max_length=40, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
    ]
