# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0004_auto_20161020_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='investdeals',
            name='admount_refund',
            field=models.DecimalField(blank=True, decimal_places=4, default='0.0', max_digits=10, null=True, verbose_name='Amount of refund'),
        ),
        migrations.AddField(
            model_name='investdeals',
            name='buy_trans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_buy', to='startpage.Trans'),
        ),
        migrations.AddField(
            model_name='investdeals',
            name='refund_trans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_refund', to='startpage.Trans'),
        ),
    ]
